/**
 * Build a Claude Code plugin from the workflow skills.
 * Produces dist/task-workflow/ (plugin dir) and dist/task-workflow.zip.
 * The zip root contains the plugin contents (.claude-plugin/ + skills/), per plugin spec.
 */
import { mkdirSync, readFileSync, rmSync, writeFileSync, readdirSync, statSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { deflateRawSync } from 'node:zlib';
import { SKILLS } from '../src/init.js';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf-8'));

const PLUGIN_NAME = 'task-workflow';
const dist = join(root, 'dist');
const pluginDir = join(dist, PLUGIN_NAME);

const skills = Object.values(SKILLS);
if (skills.length === 0) {
  throw new Error('No skills found in SKILLS');
}
for (const skill of skills) {
  const frontmatterName = /^name:\s*(\S+)/m.exec(skill.content)?.[1];
  if (!frontmatterName || frontmatterName !== skill.name) {
    throw new Error(`SKILL ${skill.name} frontmatter name mismatch: "${frontmatterName}"`);
  }
}

function writeFileTree(baseDir, path, content) {
  mkdirSync(dirname(join(baseDir, path)), { recursive: true });
  writeFileSync(join(baseDir, path), content);
}

function buildPluginDir() {
  rmSync(pluginDir, { recursive: true, force: true });
  writeFileTree(pluginDir, '.claude-plugin/plugin.json', `${JSON.stringify({
    name: PLUGIN_NAME,
    description: pkg.description,
    version: pkg.version,
    author: pkg.author,
    license: pkg.license,
    homepage: pkg.homepage,
    repository: pkg.repository.url,
    keywords: pkg.keywords,
  }, null, 2)}\n`);
  writeFileTree(pluginDir, 'README.md', `# task-workflow plugin

Skills packaged from [task-cli](https://github.com/winton979/ai-task-cli) (v${pkg.version}).

Generated by \`npm run build:plugin\` — do not edit by hand.
`);
  for (const skill of skills) {
    writeFileTree(pluginDir, `skills/${skill.name}/SKILL.md`, skill.content);
  }
}

/* ---- minimal zip writer (local headers + deflate, central directory, EOCD) ---- */

const CRC_TABLE = (() => {
  const table = new Int32Array(256);
  for (let n = 0; n < 256; n++) {
    let c = n;
    for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
    table[n] = c;
  }
  return table;
})();

function crc32(buf) {
  let c = 0xffffffff;
  for (let i = 0; i < buf.length; i++) c = CRC_TABLE[(c ^ buf[i]) & 0xff] ^ (c >>> 8);
  return (c ^ 0xffffffff) >>> 0;
}

function collectFiles(dir) {
  const files = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) {
      files.push(...collectFiles(full));
    } else {
      files.push(full);
    }
  }
  return files.sort();
}

function writeZip(zipPath, filePaths, baseDir) {
  const centralEntries = [];
  const chunks = [];
  let offset = 0;

  for (const filePath of filePaths) {
    const relative = filePath.slice(baseDir.length + 1).replaceAll('\\', '/');
    const data = readFileSync(filePath);
    const compressed = deflateRawSync(data);
    const crc = crc32(data);

    const name = Buffer.from(relative, 'utf-8');
    const local = Buffer.alloc(30);
    local.writeUInt32LE(0x04034b50, 0); // local file header signature
    // Zip header fields: signature | version | flags | method | mtime | mdate |
    // crc32 | compressed size | uncompressed size | name len | extra len
    local.writeUInt16LE(20, 4);
    local.writeUInt16LE(0x0800, 6); // UTF-8 filename flag
    local.writeUInt16LE(8, 8); // deflate
    local.writeUInt16LE(0, 10);
    local.writeUInt16LE(0, 12);
    local.writeUInt32LE(crc, 14);
    local.writeUInt32LE(compressed.length, 18);
    local.writeUInt32LE(data.length, 22);
    local.writeUInt16LE(name.length, 26);
    local.writeUInt16LE(0, 28);

    const central = Buffer.alloc(46);
    central.writeUInt32LE(0x02014b50, 0); // central directory signature
    // Central entry: signature | made-by | needed | flags | method | mtime | mdate |
    // crc32 | compressed size | uncompressed size | name len | extra len | comment len |
    // disk | internal attrs | external attrs | local header offset
    central.writeUInt16LE(20, 4);
    central.writeUInt16LE(20, 6);
    central.writeUInt16LE(0x0800, 8);
    central.writeUInt16LE(8, 10);
    central.writeUInt16LE(0, 12);
    central.writeUInt16LE(0, 14);
    central.writeUInt32LE(crc, 16);
    central.writeUInt32LE(compressed.length, 20);
    central.writeUInt32LE(data.length, 24);
    central.writeUInt16LE(name.length, 28);
    central.writeUInt16LE(0, 30);
    central.writeUInt16LE(0, 32);
    central.writeUInt16LE(0, 34);
    central.writeUInt16LE(0, 36);
    central.writeUInt32LE(0, 38);
    central.writeUInt32LE(offset, 42);

    chunks.push(local, name, compressed);
    centralEntries.push({ central, name });
    offset += local.length + name.length + compressed.length;
  }

  const centralSize = centralEntries.reduce((acc, e) => acc + e.central.length + e.name.length, 0);
  const centralStart = offset;
  for (const { central, name } of centralEntries) {
    chunks.push(central, name);
  }

  const eocd = Buffer.alloc(22);
  eocd.writeUInt32LE(0x06054b50, 0); // end of central directory signature
  // Static 4.0-compatible fields (disk numbers, entry counts, sizes, offset)
  eocd.writeUInt16LE(0, 4);
  eocd.writeUInt16LE(0, 6);
  eocd.writeUInt16LE(filePaths.length, 8);
  eocd.writeUInt16LE(filePaths.length, 10);
  eocd.writeUInt32LE(centralSize, 12);
  eocd.writeUInt32LE(centralStart, 16);
  eocd.writeUInt16LE(0, 20); // comment length
  chunks.push(eocd);

  writeFileSync(zipPath, Buffer.concat(chunks));
}

/* ---- build ---- */

buildPluginDir();

const zipPath = join(dist, `${PLUGIN_NAME}.zip`);
const filePaths = collectFiles(pluginDir);
writeZip(zipPath, filePaths, pluginDir);

console.log(`plugin  skills: ${skills.length}`);
for (const skill of skills) console.log(`  - ${skill.name}`);
console.log(`plugin  dir : ${pluginDir}`);
console.log(`zip     out: ${zipPath} (${filePaths.length} files)`);